const cors = require('cors')

const corsMiddleware = cors()

/**
 * Register API route.
 * @param {object} app - Express app instance.
 * @param {string} route - Relative route path.
 * @param {object} options - Additional options.
 * @param {'get'|'post'|'put'|'delete'} [options.method] - Route method. Default: 'get'
 * @param {object} [options.headers] - Additional response headers. Default: {}.
 * @param {[function]} [options.middleware] - Request middleware to use.
 * @param {RouteHandler} handler - Request handler.
 */
function registerRoute(app, route, options, handler) {
    const {
        method = 'get',
        headers,
        middleware = []
    } = options

    middleware.unshift(corsMiddleware)

    app[method](route, middleware, function (req, res) {
        handler(req, res)
            .then(data => {
                if (res.headersSent) //stop further processing if the response has been already generated by the handler
                    return
                if (!data) data = {}
                if (headers) {
                    res.set(headers)
                    //send raw data if content-type was specified
                    if (headers['content-type'] && headers['content-type'] !== 'application/json') {
                        res.send(data)
                        return
                    }
                }
                res.side('application/json')
                res.send(JSON.stringify(data, null, req.query.pretty_print !== undefined ? 2 : undefined))
            })
            .catch(err => {
                if (err.status)
                    return res.status(err.status).json({
                        error: err.message,
                        status: err.status
                    })
                //unhandled error
                err.message = req.url + ' \n' + err.message
                console.error(err)
                res.status(500)
                    .json({
                        error: 'Internal server error',
                        status: 500
                    })
            })
    })

    app.options(route, middleware, function (req, res) {
        res.send(method.toUpperCase())
    })
}

module.exports = {registerRoute}

/**
 * Route handler callback.
 * @callback RouteHandler
 * @param {Request} req - Request object.
 * @param {Response} [res] - Response object.
 */